### ISSUE TITLE
How to always make FAB above it?

### ISSUE THREAD

**Issue by kiaanpillay** [aurelhubert/ahbottomnavigation#38]
I am using a Coordniator layout and I have a FAB in the bottom right hand corner that I want to always be visible but when the bottom nav is shown it covers the button

**Comment by aurelhubert** [comment]
Can you show me your XML layout? The FAB should be in the container layout (in top of the bottom navigation).

**Comment by kiaanpillay** [comment]
<android.support.design.widget.AppBarLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|enterAlways"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <TabLayout
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:tabMode="fixed"
        app:tabGravity="fill"/>
</android.support.design.widget.AppBarLayout>

<ImageView
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:id="@+id/imgBG"
    android:layout_alignParentTop="true"
    android:layout_alignParentLeft="true"
    android:layout_alignParentStart="true"
    android:scaleType="fitXY" />

<android.support.v4.view.ViewPager
    android:id="@+id/viewpager"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior" />

<android.support.design.widget.FloatingActionButton
    android:id="@+id/bfEnter"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:clickable="true"
    android:src="@drawable/ic_compose"
    app:borderWidth="0dp"
    android:layout_above="@+id/bottom_navigation"
    android:layout_gravity="end|bottom"
    android:layout_alignParentRight="true"
    android:layout_marginBottom="16dp"
    android:layout_marginRight="16dp" />

<com.aurelhubert.ahbottomnavigation.AHBottomNavigation
    android:id="@+id/bottom_navigation"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>

**Comment by kiaanpillay** [comment]
Thank you so much!

**Comment by Kiran89kumar** [comment]
Is thr any update on this issue?

**Comment by aurelhubert** [comment]
@kiaanpillay @Kiran89kumar I think the CoordinatorLayout is super FrameLayout (https://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html). So the param android:layout_above="@+id/bottom_navigation" can't work.

You should maybe try to implement something like:

```xml
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:layout_scrollFlags="scroll|enterAlways"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

            <TabLayout
                android:id="@+id/tabs"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:tabGravity="fill"
                app:tabMode="fixed" />
        </android.support.design.widget.AppBarLayout>

        <ImageView
            android:id="@+id/imgBG"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true"
            android:scaleType="fitXY" />

        <android.support.v4.view.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/bfEnter"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_above="@+id/bottom_navigation"
            android:layout_alignParentRight="true"
            android:layout_gravity="end|bottom"
            android:layout_marginBottom="16dp"
            android:layout_marginRight="16dp"
            android:clickable="true"
            android:src="@drawable/ic_compose"
            app:borderWidth="0dp" />

    </FrameLayout>

    <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>
```

with all your content inside `fragment_container` except the Bottom Navigation.

**Comment by Kiran89kumar** [comment]
Thanks for replay. Still its overlapping. Bze AHBottomNavigation drawn above the fragment_container.

**Comment by aurelhubert** [comment]
I'm working on a fix which will improve the management of the FAB & Snackbar with the AHBottomNavigation.

**Comment by aurelhubert** [comment]
Fixed in 1.1.0.

**Comment by kiaanpillay** [comment]
Thanks for the quick update, I just tried it but still don't know how to get it to work?

I have used your XML with the Frame Layout but now the button just doesn't appear at all

**Comment by aurelhubert** [comment]
I suggest you to follow the example in the demo. The FAB button has a bottom margin of 72dp (56dp which is the height of the bottom nav + 16dp of margin) and the visibility is set to GONE. When you click on the second tab, the visibility of the FAB is set to VISIBLE with an animation. The key here is to the set  a bottom margin of at least 56dp to avoid to display the FAB button behind the bottom navigation.

Try to check the next files:
https://github.com/aurelhubert/ahbottomnavigation/blob/master/demo/src/main/res/layout/activity_home.xml
https://github.com/aurelhubert/ahbottomnavigation/blob/master/demo/src/main/java/com/aurelhubert/ahbottomnavigation/demo/DemoActivity.java

**Comment by kiaanpillay** [comment]
It isn't an issue of tab selection though?

My issue is that when you scroll the Bottom Nav dissapears or appears. When it appears I wanted the FAB above the nav bar and when it dissapears I want it at the bottom of the screen. The 72dp does not seem to be working

**Comment by aurelhubert** [comment]
`
It isn't an issue of tab selection though?
`
What is an issue? I'm sorry but I can't help you without seeing your layout.

**Comment by kiaanpillay** [comment]
```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/ChatBackground">


    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:layout_scrollFlags="scroll|enterAlways"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

        <TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabMode="fixed"
            app:tabGravity="fill"/>
    </android.support.design.widget.AppBarLayout>

    <ImageView
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:id="@+id/imgBG"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:scaleType="fitXY" />

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/compose"
        android:layout_gravity="end|bottom"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="72dp"
        android:layout_marginRight="16dp"
        android:clickable="true"
        android:onClick="onComposeClick"
        android:src="@drawable/ic_compose"
        app:backgroundTint="@color/PeliPink"
        app:borderWidth="0dp" />


    <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom"
        android:visibility="gone"/>

</android.support.design.widget.CoordinatorLayout>
```

I really appreciate how helpful you are being. Thank you!

My issue is with the scrolling, if you scroll down the bottom nav disappears and I want the FAB to be at the bottom. When you scroll up it reappears and I wan the FAB above the bottom nav. Tab selection isn't the problem

**Comment by kiaanpillay** [comment]
The button isn't visible at all right now no matter what I do

**Comment by aurelhubert** [comment]
I suggest you to start writing your layout with the xml here: #45

**Comment by kiaanpillay** [comment]
I have used that with no luck, also in #45 is the Frame Layout not pointless? It doesn't contain anything

**Comment by aurelhubert** [comment]
@kiaanpillay Okay, I'm maybe not clear, sorry for that.

So, the layout here #45  is very simple, it's only an example to show you how to place your components. The FrameLayout is empty because it's a container, you can put content inside with the FragmentManager (see the example in the Demo project). Check the code in the DemoActivity to see how to: https://github.com/aurelhubert/ahbottomnavigation/blob/master/demo/src/main/java/com/aurelhubert/ahbottomnavigation/demo/DemoActivity.java

Have you try to build the Demo project? If you use the next layout and the FAB is still invisible, I think the problem come from your project and not from the lib:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/floating_action_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="72dp"
        android:layout_marginRight="16dp"
        android:src="@drawable/ic_content_add" />

    <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
        android:id="@+id/bottom_navigation"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom" />

</android.support.design.widget.CoordinatorLayout>
```

**Comment by kiaanpillay** [comment]
I got it to work! I'm an idiot, I was inflating the wrong class the whole time, it wokred immediately once I chose the right class.

Basically, you were 100% correct from the start and I was being a total fool! Thank you so much and for the patience. Your update was perfect

**Comment by aurelhubert** [comment]
No problem :)

**Comment by Kiran89kumar** [comment]
@aurelhubert Tq for new upate. Its working perfect for FAB.

But I need to replace FAB with any other view which should can load ad.

**Comment by aurelhubert** [comment]
@Kiran89kumar For now, I suggest you to fork the project and update the class AHBottomNavigationBehavior (which manage the behavior for the AHBottomNavigation & Floating Action Button) for your needs, or simply add a behavior to your view (I'm not an expert with the coordinator layout yet... :) ).

**Comment by Kiran89kumar** [comment]
@aurelhubert: Thanks. By adding Proper behavior it worked for me.

Thanks a lot...

**Comment by Sasikiran238** [comment]
How to make bottom navigation in stable

**Comment by Sasikiran238** [comment]
OK  i fixed .

**Comment by bismert** [comment]
Hi everyone, I am facing another issue related to this very problem and its that, the FAB is hanging up without coming down after the snackbar is gone. The FAB is coming on top of Bottom Navigation as I have wanted. My layout is exactly as the one above #[https://github.com/aurelhubert/ahbottomnavigation/issues/38#issuecomment-209436103](url)
I changed the marginBottom to 72dp please is there any work around for this.
Thanks in anticipation.
